version: '3.1'
services:
  database:
    image: mongo
    env_file:
    - ./.env.docker
    ports:
      - 27017:27017
  database-admin-web:
    image: mongo-express
    volumes:
      - ./data:/data/db
    ports:
      - 8081:8081
    env_file:
      - ./.env.docker